version: 0.2

phases:
  install:
    commands:
      - make install
  pre_build:
    commands:
      - make format
      - make lint
  build:
    commands:
      - make test
artifacts:
  files:
    - htmlcov/**/*
  base-directory: 'htmlcov'
