version: 0.2

phases:
  install:
    commands:
      - make install
  pre_build:
    commands:
      - make format
      - make lint
  build:
    commands:
      - make test
  post_build:
    commands:
      - aws s3 cp s3://codepipeline-ap-southeast-2-810918552399/fastapi-apprunner-pi/SourceArti/
artifacts:
  files:
    - htmlcov/**/*
  base-directory: 'htmlcov'
